# Build with "snapcraft" in the root of this directory.
# Then, sudo snap install --devmode ias-ruby2-script-infra_<version>_<arch>.snap

name: ias-ruby2-script-infra
version: '0.1'
summary: Ruby2 libraries for automation infrastructure
description: |
    Ticket URL: 
    Wiki Page: 

grade: stable
confinement: devmode
base: core18

# apps:
#     ias-ruby2-script-infra_hello.sh:
#         command: src/bin/ias-ruby2-script-infra_hello.sh

parts:
    snaptest1:
        plugin: dump
        source: ./src

